FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY jest.config.js ./
COPY tsconfig.json ./

ENV NODE_ENV=development

RUN npm install --legacy-peer-deps

COPY . .

CMD ["npx", "jest", "test"]
